//Meteor.subscribe('Rankings');
//Meteor.subscribe('Images');
//
//Meteor.subscribe('CarbonStats');
//
//Meteor.subscribe('CarEfficiency');
//Meteor.subscribe('Cars');
//
//Meteor.subscribe('TreeCollection');
//Meteor.subscribe('TreeDiameter');
